### ISSUE TITLE
Handle XML nodes that inlcude hyphen

### ISSUE THREAD

**Issue by kajatiger** [Absolventa/saxophone#4] opened 2020-01-07 14:18 UTC

**Comment by kajatiger** [comment] 2020-01-07 14:20
#1 
https://github.com/Absolventa/saxophone/pull/3
https://github.com/Absolventa/uno/pull/1325

**Comment by rstammer** [comment] 2020-01-07 19:36
Hey @kajatiger, this one is a duplicate of #1, so I'll close it for clarity.

**Closed as completed by rstammer** 2020-01-07 19:36 UTC
